port: 8080

file:
  imgMaxFileSize: 10 << 20
  imgAllowExits: .jpg,.png,.jpeg
  excelMaxFileSize: 3 << 20
  excelAllowExits: .xls,.xlsx
  docMaxFileSize: 5 << 20
  docAllowExits: .doc,.docx

  imgSavePath: /Users/lzx/static/imgs/
  docSavePath: /Users/lzx/static/docs/
  excelSavePath: /Users/lzx/static/excels/

  imgPrefixUrl: http://127.0.0.1:8080/imgs/
  docPrefixUrl: http://127.0.0.1:8080/docs/
  excelPrefixUrl: http://127.0.0.1:8080/excels/




